modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="aicompanion"
version="1.0.0"
displayName="AI Companion Mod"
description='''
A Minecraft mod that adds an AI-controlled entity that players can command to perform various tasks.
'''
authors="AI Companion Dev Team"

[[dependencies.aicompanion]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aicompanion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.5,1.22)"
    ordering="NONE"
    side="BOTH"
